### ISSUE TITLE
MFC file support Request

### ISSUE THREAD

**Issue by fourniernicolas** [CSS-Electronics/canedge_browser#1]
Hi,

Can you add the MFC (MF4 compressed) file support?

**Comment by MatinF** [comment]
Hi there, thanks for your request. This is on our roadmap for `mdf_iter` and `canedge_browser` - you can "watch" the github page here for updates and commits.

**Comment by fourniernicolas** [comment]
Thank !

For a hot fix, the mdf4 specification use zlib compression, the CanEdge use a LZSS compression (https://canlogger.csselectronics.com/canedge-docs/ce2/configuration/log.html?highlight=compression#compression).

I tried with this library : https://github.com/eerimoq/pyheatshrink
`  
  if log_file.endswith(".MFC"):
        import heatshrink2
        compressed_data = fs.open(log_file, 'rb').read()
        decompressed_data =heatshrink2.decompress(compressed_data)
        log_file.replace(".MFC", ".MF4")
        fs.open(log_file, 'wb').write(decompressed_data)
`
But I fail with my decompression, do you have an idea how to do that?

**Comment by MatinF** [comment]
Hi again,

Handling decompression is a bit more complex than this as the first chunk of the header needs to be handled differently. As mentioned we will introduce this, but I can't give an ETA yet - though we do aim to have it released this year. 

If you are interested in looking further into this, you can see below implementation from another user for inspiration:

```
from heatshrink2 import HeatshrinkFile
import io
import os
import sys
# If built with PyInstaller this can be built to have the same functionality
# as the mdf2finalised.exe
# PYINSTALLER_BUILD = False

WINDOWS_SIZES = {256: 8, 512: 9, 1024: 10}

# Comment out folder_locations if building using Pyinstaller
folder_locations = ['E:/LOG/5CEE33D5/00000002', 'E:/LOG/5CEE33D5/00000003',
                    'E:/LOG/5CEE33D5/00000004', 'E:/LOG/5CEE33D5/00000005']

# Uncomment these two lines if building using pyinstaller
# if PYINSTALLER_BUILD:
# 	folder_locations = sys.argv[1:]

approved_folders = []

for folder in folder_locations:
    if os.path.isdir(folder):
        approved_folders.append(folder)

for folder in approved_folders:
    dir_contents = os.listdir(folder)
    for file in [x for x in dir_contents if x.endswith('.MFC')]:
        file_path = os.path.join(folder, file)
        file_in = open(file_path, "rb")

        header = file_in.read(28)

        look_ahead = header[20:24]
        window_size = header[24:28]

        look_ahead = int.from_bytes(look_ahead, byteorder='big', signed=False)
        window_size = int.from_bytes(window_size, byteorder='big',
                                     signed=False)
        file_data = io.BytesIO(file_in.read())
        with HeatshrinkFile(file_data, window_sz2=WINDOWS_SIZES[window_size],
                            lookahead_sz2=look_ahead) as f_in:
            new_file_name = os.path.splitext(file)[0] + '.MF4'

            with open(os.path.join(folder, new_file_name), "wb") as f_out:
                f_out.write(f_in.read())

```

**Comment by fourniernicolas** [comment]
Hi Martin,

Nothing see to work with my file with the python script, the mdf2finalized is able to extract my MF4 file.

I don’t know why, but the parser get a zero windows size, I hardcoded it with my CanEdge2 value (1024) but the decompression output is not a valid MF4 file.
***@***.***D77250.3787B630]

if log_file.endswith(".MFC"):
    from heatshrink2 import HeatshrinkFile
    import io
    import os
    import heatshrink2

    WINDOWS_SIZES = {256: 8, 512: 9, 1024: 10}
    file_in = fs.open(log_file, 'rb')
    header = file_in.read(28)

    look_ahead = header[20:24]
    window_size = header[24:28]

    look_ahead = int.from_bytes(look_ahead, byteorder='big', signed=False)
    window_size = int.from_bytes(window_size, byteorder='big',
                                 signed=False)
    #file_data = io.BytesIO(file_in.read()) # tried
    file_data = fs.open(log_file, 'rb').read()

    # tried
    #with HeatshrinkFile(file_data, window_sz2=WINDOWS_SIZES[window_size],
    #                    lookahead_sz2=look_ahead) as f_in:
    #    log_file = log_file.replace(".MFC", ".MF4")
    #    fs.open(log_file, 'wb').write(f_in.read())

    #compressed_data = fs.open(log_file, 'rb').read()
    if window_size==0:
        window_size = 256
    decompressed_data = heatshrink2.decompress(file_data, window_sz2=WINDOWS_SIZES[window_size])
    log_file = log_file.replace(".MFC", ".MF4")
    fs.open(log_file, 'wb').write(decompressed_data)

We need to decompress our files coming from CanEdge2, otherwise we are "gameover", do you have a possible solution?

Merci,
***@***.***D77250.3787B630]
Nicolas Fournier, ing.
Ingénieur Électrique
Electrical Engineer

Tel. +1 418 543.1632<tel:14185431632>

***@***.******@***.***>
www.mecfor.com <http://www.mecfor.com%20>


Service après-vente Mecfor | Mecfor After-Sale Service: ***@***.*** ***@***.***>
SAV équipement Brochot | Brochot Equipment After-sale service: ***@***.*** ***@***.***>
Pièces de rechange : ***@***.*** ***@***.***> | Spare parts: ***@***.*** ***@***.***>


Mecfor Inc., 1788, Mitis, Chicoutimi (Québec), G7K 1H5 CANADA
Mecfor Brochot SAS, 465, Parc d’activité de la Haute Rive, 59553, Cuincy, France

AVIS DE CONFIDENTIALITÉ | Ce courriel et tout document annexé sont confidentiels. Si vous les avez reçus par erreur, veuillez les détruire et en aviser l’expéditeur.
NOTICE OF CONFIDENTIALITY | This e-mail and any attached document are confidential. If you are not the intended recipient, please delete all documents and advise the sender.


De : Martin Falch ***@***.***>
Envoyé : 6 juillet 2021 09:14
À : CSS-Electronics/canedge_browser ***@***.***>
Cc : Nicolas Fournier ***@***.***>; Author ***@***.***>
Objet : Re: [CSS-Electronics/canedge_browser] MFC file support Request (#1)


Hi again,

Handling decompression is a bit more complex than this as the first chunk of the header needs to be handled differently. As mentioned we will introduce this, but I can't give an ETA yet - though we do aim to have it released this year.

If you are interested in looking further into this, you can see below implementation from another user for inspiration:

from heatshrink2 import HeatshrinkFile

import io

import os

import sys

# If built with PyInstaller this can be built to have the same functionality

# as the mdf2finalised.exe

# PYINSTALLER_BUILD = False



WINDOWS_SIZES = {256: 8, 512: 9, 1024: 10}



# Comment out folder_locations if building using Pyinstaller

folder_locations = ['E:/LOG/5CEE33D5/00000002', 'E:/LOG/5CEE33D5/00000003',

                    'E:/LOG/5CEE33D5/00000004', 'E:/LOG/5CEE33D5/00000005']



# Uncomment these two lines if building using pyinstaller

# if PYINSTALLER_BUILD:

#       folder_locations = sys.argv[1:]



approved_folders = []



for folder in folder_locations:

    if os.path.isdir(folder):

        approved_folders.append(folder)



for folder in approved_folders:

    dir_contents = os.listdir(folder)

    for file in [x for x in dir_contents if x.endswith('.MFC')]:

        file_path = os.path.join(folder, file)

        file_in = open(file_path, "rb")



        header = file_in.read(28)



        look_ahead = header[20:24]

        window_size = header[24:28]



        look_ahead = int.from_bytes(look_ahead, byteorder='big', signed=False)

        window_size = int.from_bytes(window_size, byteorder='big',

                                     signed=False)

        file_data = io.BytesIO(file_in.read())

        with HeatshrinkFile(file_data, window_sz2=WINDOWS_SIZES[window_size],

                            lookahead_sz2=look_ahead) as f_in:

            new_file_name = os.path.splitext(file)[0] + '.MF4'



            with open(os.path.join(folder, new_file_name), "wb") as f_out:

                f_out.write(f_in.read())

**Comment by MatinF** [comment]
Hi again,

I would suggest awaiting our implementation for "native" decompression. We'll try and move this forward - potentially we can look into this short-term.

Just to understand, are you unable to decompress your log files via the mdf2finalized.exe? That should work - and you can call it from inside Python as well. If you are unable to use it, please send us a log file example and the steps you've tried via our contact mail contact@csselectronics.com.

best,
Martin

**Comment by MatinF** [comment]
This has now been implemented
